### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by redhog** [team-sagil/todo#1]
* [ ] Wedding stuff
  * [ ] Tickets to Umeå
  * [ ] Take time off for wedding / organize to work from "home"
  * [ ] Book hotel
  * [ ] Outfit for Saghar
  * [ ] Outfit for Egil (ask Jesper about skirt!)
  * [ ] What are we gonna give them? Money for adventure?
* [ ] Talk to Hiva
* [ ] Douglas' student
  * [ ] Contact Katti
  * [ ] Gift? Similar stuff to what Katti gave me? Serious stuff?
  * [ ] What does Hiva do w her apt? Can we use it for this?
* [ ] Boat
  * [ ] Talk to Emelie & Gonte about moving to Norway
  * [ ] Talk to Geir about place in Fredrikstad
  * [ ] When to fix
  * [ ] When to Sail
